[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "netlify-plugin-cypress"
  
 [[redirects]]
  from = "/home*"
  to = "https://reviewsworld.net/:splat"
  status = 301
  force = true
